COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
#  SQLALCHEMY_DATABASE_URI: 'sqlite://'
#  SQLALCHEMY_DATABASE_URI: 'sqlite:///device_db.sqlite'
  SQLALCHEMY_DATABASE_URI: 'mysql://{0}:{1}@localhost/ApplianceRepairDB_Lab33'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://{0}:{1}@localhost/ApplianceRepairDB_Lab33'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: user
  MYSQL_ROOT_PASSWORD: root
